routes/web.php
<?php
use App\Http\Controllers\HomeController;
use Doctrine\DBAL\Schema\Index;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */


Route::get('/', 'HomeController@Index');

Auth::routes();

Route::get('/kulinga/admin', ['as' => 'admin.dashboard', 'uses' => 'FilmController@index']);

Route::get('admin/films', ['as' => 'admin.films.index', 'uses' => 'FilmController@index']);
Route::post('admin/films', ['as' => 'admin.films.store', 'uses' => 'FilmController@store']);
Route::get('admin/films/create', ['as' => 'admin.films.create', 'uses' => 'FilmController@create']);
Route::put('admin/films/{films}', ['as' => 'admin.films.update', 'uses' => 'FilmController@update']);
Route::patch('admin/films/{films}', ['as' => 'admin.films.update', 'uses' => 'FilmController@update']);
Route::delete('admin/films/{films}', ['as' => 'admin.films.destroy', 'uses' => 'FilmController@destroy']);
Route::get('admin/films/{films}', ['as' => 'admin.films.show', 'uses' => 'FilmController@show']);
Route::get('admin/films/{films}/edit', ['as' => 'admin.films.edit', 'uses' => 'FilmController@edit']);


Route::get('admin/prixFilms/{Films}', ['as' => 'admin.prixFilms.index', 'uses' => 'prixFilmController@index']);
Route::post('admin/prixFilms', ['as' => 'admin.prixFilms.store', 'uses' => 'prixFilmController@store']);
Route::get('admin/prixFilms/create/{Films}', ['as' => 'admin.prixFilms.create', 'uses' => 'prixFilmController@create']);
Route::put('admin/prixFilms/{prixFilms}', ['as' => 'admin.prixFilms.update', 'uses' => 'prixFilmController@update']);
Route::patch('admin/prixFilms/{prixFims}', ['as' => 'admin.prixFilms.update', 'uses' => 'prixFilmController@update']);
Route::delete('admin/prixFilms/{prixFilms}', ['as' => 'admin.prixFilms.destroy', 'uses' => 'prixFilmController@destroy']);
Route::get('admin/prixFilms/{prixFilms}', ['as' => 'admin.prixFilms.show', 'uses' => 'prixFilmController@show']);
Route::get('admin/prixFilms/{prixFilms}/edit', ['as' => 'admin.prixFilms.edit', 'uses' => 'prixFilmController@edit']);


Route::get('admin/promos', ['as' => 'admin.promos.index', 'uses' => 'PromoController@index']);
Route::post('admin/promos', ['as' => 'admin.promos.store', 'uses' => 'PromoController@store']);
Route::get('admin/promos/create', ['as' => 'admin.promos.create', 'uses' => 'PromoController@create']);
Route::put('admin/promos/{promos}', ['as' => 'admin.promos.update', 'uses' => 'PromoController@update']);
Route::patch('admin/promos/{promos}', ['as' => 'admin.promos.update', 'uses' => 'PromoController@update']);
Route::delete('admin/promos/{promos}', ['as' => 'admin.promos.destroy', 'uses' => 'PromoController@destroy']);
Route::get('admin/promos/{promos}', ['as' => 'admin.promos.show', 'uses' => 'PromoController@show']);
Route::get('admin/promos/{promos}/edit', ['as' => 'admin.promos.edit', 'uses' => 'PromoController@edit']);

Route::get('admin/auteurs', ['as' => 'admin.auteurs.index', 'uses' => 'AuteurController@index']);
Route::post('admin/auteurs', ['as' => 'admin.auteurs.store', 'uses' => 'AuteurController@store']);
Route::get('admin/auteurs/create', ['as' => 'admin.auteurs.create', 'uses' => 'AuteurController@create']);
Route::put('admin/auteurs/{auteurs}', ['as' => 'admin.auteurs.update', 'uses' => 'AuteurController@update']);
Route::patch('admin/auteurs/{auteurs}', ['as' => 'admin.auteurs.update', 'uses' => 'AuteurController@update']);
Route::delete('admin/auteurs/{auteurs}', ['as' => 'admin.auteurs.destroy', 'uses' => 'AuteurController@destroy']);
Route::get('admin/auteurs/{auteurs}', ['as' => 'admin.auteurs.show', 'uses' => 'AuteurController@show']);
Route::get('admin/auteurs/{auteurs}/edit', ['as' => 'admin.auteurs.edit', 'uses' => 'AuteurController@edit']);


Route::get('admin/abonnements', ['as' => 'admin.abonnements.index', 'uses' => 'AbonnementController@index']);
Route::post('admin/abonnements', ['as' => 'admin.abonnements.store', 'uses' => 'AbonnementController@store']);
Route::get('admin/abonnements/create', ['as' => 'admin.abonnements.create', 'uses' => 'AbonnementController@create']);
Route::put('admin/abonnements/{abonnements}', ['as' => 'admin.abonnements.update', 'uses' => 'AbonnementController@update']);
Route::patch('admin/abonnements/{abonnements}', ['as' => 'admin.abonnements.update', 'uses' => 'AbonnementController@update']);
Route::delete('admin/abonnements/{abonnements}', ['as' => 'admin.abonnements.destroy', 'uses' => 'AbonnementController@destroy']);
Route::get('admin/abonnements/{abonnements}', ['as' => 'admin.abonnements.show', 'uses' => 'AbonnementController@show']);
Route::get('admin/abonnements/{abonnements}/edit', ['as' => 'admin.abonnements.edit', 'uses' => 'AbonnementController@edit']);


Route::get('admin/typeAbonnements', ['as' => 'admin.typeAbonnements.index', 'uses' => 'TypeAbonnementController@index']);
Route::post('admin/typeAbonnements', ['as' => 'admin.typeAbonnements.store', 'uses' => 'TypeAbonnementController@store']);
Route::get('admin/typeAbonnements/create', ['as' => 'admin.typeAbonnements.create', 'uses' => 'TypeAbonnementController@create']);
Route::put('admin/typeAbonnements/{typeAbonnements}', ['as' => 'admin.typeAbonnements.update', 'uses' => 'TypeAbonnementController@update']);
Route::patch('admin/typeAbonnements/{typeAbonnements}', ['as' => 'admin.typeAbonnements.update', 'uses' => 'TypeAbonnementController@update']);
Route::delete('admin/typeAbonnements/{typeAbonnements}', ['as' => 'admin.typeAbonnements.destroy', 'uses' => 'TypeAbonnementController@destroy']);
Route::get('admin/typeAbonnements/{typeAbonnements}', ['as' => 'admin.typeAbonnements.show', 'uses' => 'TypeAbonnementController@show']);
Route::get('admin/typeAbonnements/{typeAbonnements}/edit', ['as' => 'admin.typeAbonnements.edit', 'uses' => 'TypeAbonnementController@edit']);


Route::get('admin/categories', ['as' => 'admin.categories.index', 'uses' => 'CategorieController@index']);
Route::post('admin/categories', ['as' => 'admin.categories.store', 'uses' => 'CategorieController@store']);
Route::get('admin/categories/create', ['as' => 'admin.categories.create', 'uses' => 'CategorieController@create']);
Route::put('admin/categories/{categories}', ['as' => 'admin.categories.update', 'uses' => 'CategorieController@update']);
Route::patch('admin/categories/{categories}', ['as' => 'admin.categories.update', 'uses' => 'CategorieController@update']);
Route::delete('admin/categories/{categories}', ['as' => 'admin.categories.destroy', 'uses' => 'CategorieController@destroy']);
Route::get('admin/categories/{categories}', ['as' => 'admin.categories.show', 'uses' => 'CategorieController@show']);
Route::get('admin/categories/{categories}/edit', ['as' => 'admin.categories.edit', 'uses' => 'CategorieController@edit']);

Route::get('admin/notations', ['as' => 'admin.notations.index', 'uses' => 'NotationController@index']);
Route::post('admin/notations', ['as' => 'admin.notations.store', 'uses' => 'NotationController@store']);
Route::get('admin/notations/create', ['as' => 'admin.notations.create', 'uses' => 'NotationController@create']);
Route::put('admin/notations/{notations}', ['as' => 'admin.notations.update', 'uses' => 'NotationController@update']);
Route::patch('admin/notations/{notations}', ['as' => 'admin.notations.update', 'uses' => 'NotationController@update']);
Route::delete('admin/notations/{notations}', ['as' => 'admin.notations.destroy', 'uses' => 'NotationController@destroy']);
Route::get('admin/notations/{notations}', ['as' => 'admin.notations.show', 'uses' => 'NotationController@show']);
Route::get('admin/notations/{notations}/edit', ['as' => 'admin.notations.edit', 'uses' => 'NotationController@edit']);


Route::get('admin/users', ['as' => 'admin.users.index', 'uses' => 'UsersController@index']);
Route::post('admin/users', ['as' => 'admin.users.store', 'uses' => 'UsersController@store']);
Route::get('admin/users/create', ['as' => 'admin.users.create', 'uses' => 'UsersController@create']);
Route::put('admin/users/{users}', ['as' => 'admin.users.update', 'uses' => 'UsersController@update']);
Route::patch('admin/users/{users}', ['as' => 'admin.users.update', 'uses' => 'UsersController@update']);
Route::delete('admin/users/{users}', ['as' => 'admin.users.destroy', 'uses' => 'UsersController@destroy']);
Route::get('admin/users/{users}', ['as' => 'admin.users.show', 'uses' => 'UsersController@show']);
Route::get('admin/users/{users}/edit', ['as' => 'admin.users.edit', 'uses' => 'UsersController@edit']);



Route::resource('voirs', 'RegarderFilmsController');
Route::resource('menus', 'MenuController');



Route::get('kulinga/espace_abonne', ['as' => 'espace.abonne.index', 'uses' => 'EspaceAbonneController@index']);
Route::get('kulinga/abonne', ['as' => 'espace.abonne.home', 'uses' => 'EspaceAbonneController@index']);
Route::get('kulinga/abonnement/create', ['as' => 'espace.abonne.create', 'uses' => 'EspaceAbonneController@create']);
Route::post('kulinga/abonnement/store', ['as' => 'espace.abonne.store', 'uses' => 'EspaceAbonneController@store']);
Route::post('kulinga/abonnement', ['as' => 'espace.abonne.renouveller', 'uses' => 'EspaceAbonneController@edit']);
Route::get('kulinga/abonnement/profil', ['as' => 'espace.abonne.profil', 'uses' => 'EspaceAbonneController@profile']);
Route::patch('kulinga/abonnement/update', ['as' => 'espace.abonne.update', 'uses' => 'EspaceAbonneController@update']);

Route::resource('type_film', 'TypeFilmController');
Route::resource('avis_abonne', 'AvisabonneController');

app/Models/Film.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Class Film
 * @package App\Models\Admin
 * @version December 29, 2018, 5:11 am UTC
 *
 * @property string titre
 * @property string description
 * @property string|\Carbon\Carbon date_realisation
 * @property integer duree_film
 * @property bigInteger nb_vues
 * @property string type_film
 * @property string url_film
 * @property string pub_key_film
 * @property string url_image
 * @property string pub_key_image
 * @property integer user_id
 * @property integer auteur_id
 */
class Film extends Model
{

    public $table = 'films';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    public $fillable = [
        'titre',
        'description',
        'date_realisation',
        'duree_film',
        'nb_vues',
        'url_film',
        'pub_key_film',
        'url_image',
        'pub_key_image',
        'identite_distributeur',
        'adresse_distributeur',
        'contact_distributeur',
        'user_id',
        'auteur_id',
        'type_film_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'titre' => 'string',
        'description' => 'string',
        'duree_film' => 'integer',
        'url_film' => 'string',
        'pub_key_film' => 'string',
        'url_image' => 'string',
        'identite_distributeur' => 'string',
        'adresse_distributeur' => 'string',
        'contact_distributeur' => 'string',
        'pub_key_image' => 'string',
        'user_id' => 'integer',
        'auteur_id' => 'integer',
        'type_film_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'titre'=>'required',
        'type_film'=>'required',
        'url_film'=> "required|mimes:mp4|between:1, 100048",
        'url_image'=> "required|mimes:jpeg,bmp,jpg,png|between:1, 2048",
        'type_film_id' =>'required'
    ];

    public function user() : BelongsTo {
        return $this->belongsTo('App\Models\User');
    }

    public function typefilm() : BelongsTo {
        return $this->belongsTo('App\Models\TypeFilm');
    }

    public function auteur() : BelongsTo {
        return $this->belongsTo('App\Models\Auteur');
    }

    public function notations() : HasMany {
        return $this->hasMany('App\Models\Notation');
    }

    public function prixFilms() : HasMany {
        return $this->hasMany('App\Models\PrixFilm');
    }

    public function categories() : BelongsToMany {
        return $this->belongsToMany('App\Models\Categorie', 'categorie_has_films');
    }
}

resources/views/films/footerliste.blade.php
<!--<div class="section section_banners scrollreveal scrollAnimateFade">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-sm-6">
                <div class="bnr-container">
                    <a href="#">
                        <div class="lazy-img banner-image">
                            <img data-original="images/banner_01.jpg" src="#" alt="banner image"> </div>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="bnr-container">
                    <a href="#">
                        <div class="lazy-img banner-image">
                            <img data-original="images/banner_02.jpg" src="#" alt="banner image"> </div>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="bnr-container">
                    <a href="#">
                        <div class="lazy-img banner-image">
                            <img data-original="images/banner_03.jpg" src="#" alt="banner image"> </div>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="bnr-container">
                    <a href="#">
                        <div class="lazy-img banner-image">
                            <img data-original="images/banner_04.jpg" src="#" alt="banner image"> </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>-->
<div class="section info-block scrollreveal scrollAnimateFade">
    <div class="container">
        <h3>The Electric Ant is a science fiction short story by Philip K.</h3>
        <div class="row">
            <div class="col-lg-4 col-sm-6">
                <div class="info-block__col">
                    <p> Garson Poole wakes up after a flying-car-crash to find that he is missing a hand. He then finds out that he is an 'electric ant' – an "organic" robot. He further finds out that what he believes is his subjective reality is being
                        fed to him from a micro-punched tape in his chest cavity. He experiments on this tape by adding new holes, which adds things to his reality. </p>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="info-block__col">
                    <p> Convinced that his entire reality is constrained by the tape, he makes a major change to it, with a major effect on his reality. The change affects everyone else he interacts with, which raises the question of whether any of them
                        – or he himself – are "real" at all. </p>
                </div>
            </div>
            <div class="col-lg-4 hidden-md hidden-sm hidden-xs">
                <div class="info-block__col">
                    <p> Convinced that his entire reality is constrained by the tape, he makes a major change to it, with a major effect on his reality. The change affects everyone else he interacts with, which raises the question of whether any of them
                        – or he himself – are "real" at all. </p>
                </div>
            </div>
        </div>
        <div class="seo-spoiler">
            <div class="seo-spoiler__wrap">
                <div class="seo-spoiler__text">
                    <p> Apparently we had reached a great height in the atmosphere, for the sky was a dead black, and the stars had ceased to twinkle. By the same illusion which lifts the horizon of the sea to the level of the spectator on a hillside, the
                        sable cloud beneath was dished out, and the car seemed to float in the middle of an immense dark sphere, whose upper half was strewn with silver. Looking down into the dark gulf below, I could see a ruddy light streaming through
                        a rift in the clouds. </p>
                    <p> Apparently we had reached a great height in the atmosphere, for the sky was a dead black, and the stars had ceased to twinkle. By the same illusion which lifts the horizon of the sea to the level of the spectator on a hillside, the
                        sable cloud beneath was dished out, and the car seemed to float in the middle of an immense dark sphere, whose upper half was strewn with silver. Looking down into the dark gulf below, I could see a ruddy light streaming through
                        a rift in the clouds. </p>
                </div>
            </div>
            <div class="seo-spoiler__link-center">
                <a href="#" class="seo-spoiler__link">Show more</a>
            </div>
        </div>
    </div>
</div>

resources/views/films/lastestview.blade.php
<div class="section videos-section scrollreveal scrollAnimateFade">
    <div class="container">
        <div class="section__inner">
            <div class="section-heading">
                <h4>Latest</h4>
                <a href="#" class="section-heading__control section-heading__see-all"> See all </a>
            </div>
            <div class="row row--flex">
                <div class="col-lg-4 col-sm-6">
                    <a href="./video.html" class="video-preview video-preview--md js-ajax-link">
                        <div class="video-preview__image">
                            <span class="lazy-bg-img" data-original="images/photo_05.jpg"></span>
                            <div class="video-preview__info">
                                <div class="video-preview__duration">12:04</div>
                                <div class="video-preview__likes">88%</div>
                                <div class="video-preview__quality">HD</div>
                            </div>
                        </div>
                        <h5 class="video-preview__descr">People rejoice at the Sun, and I’m dreaming of the Moon</h5>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="./video.html" class="video-preview video-preview--md js-ajax-link">
                        <div class="video-preview__image">
                            <span class="lazy-bg-img" data-original="images/photo_07.jpg"></span>
                            <div class="video-preview__info">
                                <div class="video-preview__duration">12:04</div>
                                <div class="video-preview__likes">88%</div>
                                <div class="video-preview__quality">HD</div>
                            </div>
                        </div>
                        <h5 class="video-preview__descr">One word frees us of all the weight and pain of life: that word is love</h5>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="./video.html" class="video-preview video-preview--md js-ajax-link">
                        <div class="video-preview__image">
                            <span class="lazy-bg-img" data-original="images/photo_08.jpg"></span>
                            <div class="video-preview__info">
                                <div class="video-preview__duration">12:04</div>
                                <div class="video-preview__likes">88%</div>
                                <div class="video-preview__quality">HD</div>
                            </div>
                        </div>
                        <h5 class="video-preview__descr">Always forgive your enemies — nothing annoys them so much</h5>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="./video.html" class="video-preview video-preview--md js-ajax-link">
                        <div class="video-preview__image">
                            <span class="lazy-bg-img" data-original="images/photo_09.jpg"></span>
                            <div class="video-preview__info">
                                <div class="video-preview__duration">12:04</div>
                                <div class="video-preview__likes">88%</div>
                                <div class="video-preview__quality">HD</div>
                            </div>
                        </div>
                        <h5 class="video-preview__descr">He, who does not love loneliness, does not love freedom</h5>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="./video.html" class="video-preview video-preview--md js-ajax-link">
                        <div class="video-preview__image">
                            <span class="lazy-bg-img" data-original="images/photo_10.jpg"></span>
                            <div class="video-preview__info">
                                <div class="video-preview__duration">12:04</div>
                                <div class="video-preview__likes">88%</div>
                                <div class="video-preview__quality">HD</div>
                            </div>
                        </div>
                        <h5 class="video-preview__descr">A dream becomes a goal when action is taken toward its achievement</h5>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="./video.html" class="video-preview video-preview--md js-ajax-link">
                        <div class="video-preview__image">
                            <span class="lazy-bg-img" data-original="images/photo_11.jpg"></span>
                            <div class="video-preview__info">
                                <div class="video-preview__duration">12:04</div>
                                <div class="video-preview__likes">88%</div>
                                <div class="video-preview__quality">HD</div>
                            </div>
                        </div>
                        <h5 class="video-preview__descr">People rejoice at the Sun, and I’m dreaming of the Moon</h5>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/films/listsFilmsByCategorie.blade.php
@extends('layouts.frontEnd')
@section('styles')
    	<style type="text/css">
  		.scroll1{
  			overflow-y: scroll;
            height: 600px;
  		}
  	</style>
@endsection
@section('content')
    <div class="section videos-section scrollreveal scrollAnimateFade">
        <div class="container">
            <div class="section__inner">
                <div class="section-heading">
                    @if (isset($macategorie))
                        <h4>New {{ strtolower($macategorie->libelle) }} videos</h4>
                    @else
                        <h4>News videos</h4>
                    @endif
                </div>
                <div class="row">
                <div id="paginate1" class="scroll1">
                    @include('films.news')
                </div>
                </div>
              {{--<div class="text-center">{{$news->links()}}</div>--}} 
            </div>

             <div class="section__inner">
                <div class="section-heading">
                    @if (isset($macategorie))
                        <h4>Most {{ strtolower($macategorie->libelle) }} viewed</h4>
                    @else
                        <h4>Most viewed</h4>
                    @endif
                </div>
                <div class="row">
                <div id="paginate2" class="scroll2">
                    @include('films.mostview')
                </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
<script>
/*$(document).ready(function(){
     $('.pagination a').on('click', function (e) {
            e.preventDefault();
           var page=$(this).attr('href').split('page=')[1];
            paginate_data(page);
        });
    });
  function paginate_data(page)
   {
        $.ajax({
            url :"?page="+page,
            type : 'get',
        }).done(function (data) {
            $('#paginate1').html(data);
        }).fail(function(){
             $('#paginate1').html('Aucune donnée');
        });
     }*/
</script>
@endsection

resources/views/films/mostview.blade.php
@foreach ( $mosts as $film )
                        @if ($film->nb_vues>=5)
                            <div class="col-xl-3 col-lg-4 col-sm-6">
                                <a href="{!! route('voirs.show', $film->id) !!}"
                                   class="video-preview video-preview--md">
                                    <div class="video-preview__image">
                                        <span class="lazy-bg-img"
                                              data-original="{{ asset('uploads/images/'.$film->pub_key_image) }}"></span>
                                        <div class="video-preview__info">
                                            <div class="video-preview__duration">12:04</div>
                                            <div class="video-preview__likes">88%</div>
                                            <div class="video-preview__quality">{{ $film->nb_vues }} vues</div>
                                        </div>
                                    </div>
                                    <h5 class="video-preview__descr">{{ $film->description }} </h5>
                                </a>
                            </div>
                        @endif
                    @endforeach

resources/views/films/news.blade.php
@foreach ( $news as $film )
                        @if ($film->nb_vues<=5)
                            <div class="col-xl-3 col-lg-4 col-sm-6">
                                <a href="{!! route('voirs.show', $film->id) !!}"
                                   class="video-preview">
                                    <div class="video-preview__image">
                                        <span class="lazy-bg-img"
                                              data-original="{{ asset('uploads/images/'.$film->pub_key_image) }}"></span>
                                        <div class="video-preview__info">
                                            <div class="video-preview__duration">12:04</div>
                                            <div class="video-preview__likes">88%</div>
                                            <div class="video-preview__quality">{{ $film->nb_vues }} vues</div>
                                        </div>
                                    </div>
                                    <h5 class="video-preview__descr">{{ $film->description }} </h5>
                                </a>
                            </div>
                        @endif
                    @endforeach

resources/views/films/showFilms.blade.php
@extends('layouts.frontEnd')
@section('styles')
    <link href="{{asset('css/video-js.min.css')}}" rel="stylesheet">
    <style>
        @media screen and (min-width: 960px) {
            .video-js .vjs-tech {
                position: absolute;
                left: 0;
                width: 100%;
                height: 100%;
            }

            .scroll {
                padding-left: 10%;
                padding-top: 15px;
                margin-top: 25px;
            }
        }

        @media screen and (max-width: 960px) {
            #video {
                height: 350px !important;
            }

            .video-js .vjs-tech {
                position: absolute;
                width: 400px !important;
                left: 0;
            }

            .vjs-poster {
                width: 400px !important;
            }

            .scroll {
                padding-left: 20%;
                padding-top: 15px;
                margin-top: 25px;
            }
        }

        .scroll {
            overflow-y: scroll;
            height: 800px;
            border: solid 1px white;
        }
    </style>
@endsection
@section('content')
    <div class="section videos-section scrollreveal scrollAnimateFade container-fluid">
        <div class="row">
            <div class="col-sm-8 container">
                <video id="video"
                       class="video-js"
                       width="960" height="auto"
                       preload="auto"
                       controls
                       poster="{{asset('uploads/images/'.$monfilm->pub_key_image) }}"
                       data-setup='{}'>
                    <source src="{{ asset('uploads/films/'.$monfilm->pub_key_film) }}"/>
                </video>
                <h5 class="video-preview__descr">{{ $monfilm->titre }}</h5>
                <div class="video-preview__quality">{{ $monfilm->nb_vues }} Vues</div>
            </div>
            <div class="col-sm-4 scroll">
                @foreach ($films as $film)
                    <a href="{{ route('voirs.show', $film->id)}}" class="video-preview js-ajax">
                        <video width="250" height="auto"
                               class="vidoe-js"
                               preload="auto"
                               poster="{{ asset('uploads/images/'.$film->pub_key_image) }}">
                            <source src="{{asset('uploads/films/'.$film->pub_key_film) }}"/>
                        </video>
                        <h6 class="video-preview__descr">{{ $film->description }}</h6>
                    </a>
                @endforeach
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{asset('js/video.min.js')}}"></script>
    <script>
        videojs('video');
        //eviter la copie des liens de la video
        $(function () {
            $('video').bind('contextmenu', function (e) {
                return false;
            });
        });
    </script>
@endsection